### PR TITLE
Fixed bug that prevented send of customObjects

### LINKED ISSUE #77: Support for CustomObjects
#### Description:

@alelom , apologies, assume covered by another issue/PR, but thought I'd raise here in the interest of reporting whilst I'm looking at the adapter (looking great!). I've tested pull/push bar, and custom object and bar works but custom object doesn't (with two text properties). Error message on push below (strange as I'm pushing a bar!). 

1. This component failed to run properly.
- Error: The best overloaded method match for 'BH.Engine.Speckle.Compute.BHoMRepresentation(BH.oM.Structure.Elements.Bar, BH.oM.Speckle.SpeckleDisplayOptions)' has some invalid arguments
- Occured in  BH.Engine.Speckle.Compute.SpeckleRepresentation(IBHoMObject bhomObject, SpeckleDisplayOptions displayOptions)
     called from BH.Adapter.Speckle.SpeckleAdapter.Create(IBHoMObject bhomObject, SpecklePushConfig config)
- Are you sure you have the correct type of inputs? Check their description for more details.

image

### LINKED ISSUE #83: Update copy locals and remove reference to common/unused items
#### Description:

A lot of dlls go into the Build folder on build, can we check and make sure copy local is set to false for everything not needed, and remove old/unused references?

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #77 
Closes #83 

Fixes simple bug that prevented the send of CustomObjects. It was an incorrectly named fallback case, plus a catch for empty `CompositeGeometry`.

### Test files

Just try to push a CustomObject as in #77.

### CODE REVIEW

**Comment by al-fisher** [comment]
Hey @alelom - as mentioned Push CustomObject is now working! 
Pull is giving strange behaviour though
image

**Comment by alelom** [comment]
In order to avoid that the Hash generated for CustomObject remains always the same (due to the fact that we are ignoring `CustomData` when generating it, and all of the properties of a CustomObject are in CustomData) we need to remove the field from the **default** values of `BH.oM.DiffConfig`.
Opening separate PR.

**Comment by alelom** [comment]
@al-fisher with https://github.com/BHoM/BHoM/pull/846, the CustomObject will be uploaded correctly every time a push is done.

The other issue (geometry error when nested CustomObject are input) is solved in the previous commit (https://github.com/BHoM/Speckle_Toolkit/pull/82/commits/1a119b3278e59cd2a062c3500e0aa5653b6c235a).

**Comment by al-fisher** [comment]
As per
image

**Comment by al-fisher** [comment]
@rwemay FYI

**Pull request merged**
