### PR TITLE
Basic geometry convert and Structural Elements visualisation

### LINKED ISSUE #21: Speckle_Toolkit: Converts fromBHoM toSpeckle
- Meshes

### PR DESCRIPTION
**Pull request by izzylys**
### Note: Depends on
https://github.com/BHoM/BHoM_Engine/pull/1386

### Issues addressed by this PR

Closes #21 
Closes https://github.com/BHoM/Speckle_Toolkit/issues/40 

Adds conversions for point (and vector), line, and mesh from BHoM to Speckle and back,
and basic visualisation in the SpeckleViewer for few BHoMObject types.

### Test files
[Download script](https://github.com/BHoM/Speckle_Toolkit/blob/3669985b10f7660e499c707b3506b15def648f85/Test%20Scripts/%2339-GeometryConversionAndVisualisation/%2339-GeomConvAndVisualiz-afterAdapterAlignment.gh?raw=true)

### Changelog

- `ToSpeckle` and `ToBHoM` for point, line, and mesh added to `Speckle_Engine`
- Basic visualisation in the SpeckleViewer for few BHoMObject types.

### Additional comments
Not quite sure how to register the conversion methods so they show up in the UI (Grasshopper). @alelom could you please let me know where I need to do this? At the mo, only the two first `ToBHoM` methods that were initially there are showing up as options in the convert component. Once I'm able to call them in GH, I'll test and add a script to validate that the conversions are working.

### CODE REVIEW

**Comment by alelom** [comment]
This is great @izzylys , thanks a lot!!

> Not quite sure how to register the conversion methods so they show up in the UI (Grasshopper). @alelom could you please let me know where I need to do this? At the mo, only the two first `ToBHoM` methods that were initially there are showing up as options in the convert component. Once I'm able to call them in GH, I'll test and add a script to validate that the conversions are working.

I actually manage to get your new `ToBHoM` methods: 
image

just be sure you close Rhino and rebuild BHoM_UI for the changes to appear.

What I can't get are the `ToSpeckle` methods, but that's because they need to be named `FromBHoM` instead in order to be found.
image

> Test files
> None as of yet. @alelom how should tests be done?

For now I'd say our target should be to send a BHoM element such a `Bar` to Speckle online and visualise it in its viewer.

I'll keep reviewing and testing, this looks amazing already, thanks again! 😄

**Comment by alelom** [comment]
@izzylys getting there! Thanks to your converts we can send stuff effectively!
Some more work was needed because of the underlying bhom complexity -- get the geometry out of objects is not hard, but treating the different cases and also make Speckle happy can be tedious. 

Feel free to have a look at the code -- happy to have a skype to discuss & get feedback and ideas! 😄 

image
image
image

**Comment by al-fisher** [comment]
Fantastic! Great work @izzylys @alelom! 😄 
Excited to play with this!

**Comment by alelom** [comment]
Added `Node` support basic representation and `Bar` support basic representation:

image

**Comment by alelom** [comment]
@izzylys, @al-fisher this is now ready for review!

**Comment by al-fisher** [comment]
Cool - thanks @alelom

**Comment by alelom** [comment]
Thanks @al-fisher ! Will definitely keep working on improving and defining the next steps!

**Pull request merged**
