### PR TITLE
Update Copyright Header to 2021

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #97

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by FraserGreenroyd — APPROVED** [review]
LGTM, will leave to @alelom to review/merge within 5 days.

**Review by alelom — APPROVED** [review]
LGTM.

**Pull request merged**
